import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { CmsConfig, CollectionDefinition, FieldDefinition } from '@kritano/cms/types'
import { log } from '../utils/logger'
import { loadConfig, getCmsRoot } from '../utils/config'

function fieldToTsType(field: FieldDefinition): string {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'slug':
    case 'url':
    case 'select':
    case 'colour':
      return field.nullable ? 'string | null' : 'string'
    case 'richText':
      return 'Record<string, unknown>'
    case 'number':
      return field.nullable ? 'number | null' : 'number'
    case 'boolean':
      return 'boolean'
    case 'datetime':
      return field.nullable ? 'string | null' : 'string'
    case 'multiSelect':
      return 'string[]'
    case 'media':
    case 'relation':
      return 'string | null'
    case 'seoBlock':
      return 'import("@kritano/cms/types").SeoBlock | null'
    case 'blocks':
      return 'import("@kritano/cms/types").Block[]'
    case 'array':
      return 'unknown[]'
  }
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function generateCollectionType(collection: CollectionDefinition): string {
  const typeName = capitalize(collection.name)
  const lines = [
    `export interface ${typeName} extends Document {`,
  ]

  for (const [name, field] of Object.entries(collection.fields)) {
    const tsType = fieldToTsType(field)
    lines.push(`  ${name}: ${tsType}`)
  }

  lines.push('}')
  return lines.join('\n')
}

function generateTypes(config: CmsConfig): string {
  const parts = [
    '// Auto-generated by `cms generate` — do not edit manually',
    `// Generated at: ${new Date().toISOString()}`,
    '',
    'import type { Document } from "@kritano/cms/types"',
    '',
  ]

  for (const collection of config.collections) {
    parts.push(generateCollectionType(collection))
    parts.push('')
  }

  // Collection name union
  const names = config.collections.map((c) => `'${c.name}'`).join(' | ')
  parts.push(`export type CollectionName = ${names}`)
  parts.push('')

  // Type map
  parts.push('export interface CollectionTypeMap {')
  for (const collection of config.collections) {
    parts.push(`  ${collection.name}: ${capitalize(collection.name)}`)
  }
  parts.push('}')

  return parts.join('\n')
}

export async function generate() {
  log.header('Generating types')

  try {
    const config = await loadConfig()
    const cmsRoot = getCmsRoot()

    const outputDir = resolve(cmsRoot, 'packages/sdk/src/generated')
    await mkdir(outputDir, { recursive: true })

    const outputPath = resolve(outputDir, 'collections.ts')
    const content = generateTypes(config)
    await writeFile(outputPath, content, 'utf-8')

    log.success(`Types written to packages/sdk/src/generated/collections.ts`)
    log.step(`${config.collections.length} collection(s): ${config.collections.map((c) => c.name).join(', ')}`)
  } catch (err: any) {
    log.error(`Failed: ${err.message}`)
    process.exit(1)
  }
}

// Run directly
if (import.meta.main) {
  await generate()
}
