import { writeFile, rename, readFile, unlink } from 'node:fs/promises'
import { getClient } from '../db/client'

// Opt-in: only fires when NGINX_REDIRECTS_SNIPPET points at a writable file
// included by the server's nginx config. Self-hosted nginx only; safe no-op
// elsewhere.
const ENV_KEY = 'NGINX_REDIRECTS_SNIPPET'

// Restrict to standard URL-path characters. Anything outside this set could
// break the nginx config (semicolons, braces, quotes) or be ambiguous to
// parse, so we drop those rows from the snippet rather than risk a bad reload.
const SAFE_PATH = /^\/[A-Za-z0-9\-._~%/!$&'()*+,;=:@?#]*$/

type RedirectRow = { from_path: string; to_path: string; type: number }

function snippetPath(): string | null {
  return process.env[ENV_KEY] || null
}

function safePath(p: unknown): p is string {
  return typeof p === 'string' && p.length > 0 && p.length <= 2048 && SAFE_PATH.test(p)
}

function buildSnippet(rows: RedirectRow[]): string {
  const lines = [
    '# Auto-generated by Kritano CMS — do not edit by hand.',
    '# Managed via /admin/redirects. Regenerated on every save.',
    '',
  ]
  let skipped = 0
  for (const r of rows) {
    if (!safePath(r.from_path) || !safePath(r.to_path)) {
      skipped++
      continue
    }
    const code = r.type === 302 ? 302 : 301
    lines.push(`location = ${r.from_path} { return ${code} ${r.to_path}; }`)
  }
  if (skipped > 0) {
    lines.push('')
    lines.push(`# ${skipped} redirect(s) skipped — disallowed path characters`)
  }
  lines.push('')
  return lines.join('\n')
}

async function runCmd(cmd: string[]): Promise<{ ok: boolean; stderr: string }> {
  try {
    const proc = Bun.spawn(cmd, { stderr: 'pipe', stdout: 'pipe' })
    await proc.exited
    const stderr = await new Response(proc.stderr).text()
    return { ok: proc.exitCode === 0, stderr }
  } catch (err) {
    return { ok: false, stderr: String(err) }
  }
}

// Coalesce: if a rebuild is already running, queue exactly one more after it
// finishes. Prevents a thundering herd if many redirects are imported at once.
let inFlight: Promise<void> | null = null
let pending = false

export function rebuildNginxRedirects(): Promise<void> {
  if (!snippetPath()) return Promise.resolve()
  if (inFlight) {
    pending = true
    return inFlight
  }
  inFlight = doRebuild().finally(() => {
    inFlight = null
    if (pending) {
      pending = false
      rebuildNginxRedirects().catch(() => {})
    }
  })
  return inFlight
}

async function doRebuild(): Promise<void> {
  const path = snippetPath()
  if (!path) return

  let rows: RedirectRow[]
  try {
    const result = await getClient()`SELECT from_path, to_path, type FROM redirects ORDER BY from_path`
    rows = result as unknown as RedirectRow[]
  } catch (err) {
    console.warn(`[nginx-redirects] DB read failed: ${err}`)
    return
  }

  const content = buildSnippet(rows)

  let prev: string | null = null
  try {
    prev = await readFile(path, 'utf8')
  } catch {
    prev = null
  }

  if (prev === content) return

  const tmp = `${path}.tmp`
  try {
    await writeFile(tmp, content, 'utf8')
    await rename(tmp, path)
  } catch (err) {
    console.warn(`[nginx-redirects] Write failed: ${err}`)
    return
  }

  const test = await runCmd(['sudo', '-n', 'nginx', '-t'])
  if (!test.ok) {
    console.warn(`[nginx-redirects] nginx -t rejected new snippet, restoring previous. stderr: ${test.stderr.trim()}`)
    try {
      if (prev !== null) {
        await writeFile(path, prev, 'utf8')
      } else {
        await unlink(path).catch(() => {})
      }
    } catch (err) {
      console.warn(`[nginx-redirects] Restore failed: ${err}`)
    }
    return
  }

  const reload = await runCmd(['sudo', '-n', 'nginx', '-s', 'reload'])
  if (!reload.ok) {
    console.warn(`[nginx-redirects] nginx -s reload failed: ${reload.stderr.trim()}`)
    return
  }

  console.log(`[nginx-redirects] Reloaded with ${rows.length} redirect(s)`)
}
